import type { Metadata } from "next";
import { Poppins } from "next/font/google"
import "./globals.css";
import Header from "@/components/header/Header";
import { Toaster } from "react-hot-toast";
import Provider from "@/redux/provider";
import EcommerceFooter from "@/components/common/Footer";

const poppins = Poppins({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-sans"
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} bg-gray-100`}
      >
        <Provider>
          <Header />
          {children}
          <Toaster position="top-center" />
          <EcommerceFooter />
        </Provider>
      </body>
    </html>
  );
}
