import type { Metadata } from "next";
import {Poppins} from "next/font/google"
import "./globals.css";
import Header from "@/components/header/Header";

const poppins = Poppins({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-sans"
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} bg-gray-100`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
